export const API_END_POINTS = {
  AUTH: {
    LOGIN: 'login',
    FORGOT_PASSWORD: 'forgot-password',
    VERIFY_PASSWORD_KEY: 'verify-password-key',
    SET_RESET_PASSWORD: 'set-password',
  },
  ADMIN: {
    PROFILE: 'profile',
    SUSPEND: 'suspend',
    CHANGE_PASSWORD: 'change-password',
    NOTIFICATION: 'notification',
    DASHBOARD: 'dashboard',
    KYC: 'kyc',
    ERROR_LOGS: {
      ERROR_LOGS: 'error-logs',
      ERROR_LOGS_MAIL: 'error-logs/email',
    },
    APPS: 'apps',
    ROLE: {
      GET_ROLE: 'role',
      DELETE_ROLE: 'role/delete',
    },
    USER_SHORTCUT: {
      USER_SHORTCUT: 'user-shortcut',
      DELETE_USER_SHORTCUT: 'role/user-shortcut',
      RANK_USER_SHORTCUT: 'user-shortcut/rank',
    },
    CUSTOMER: {
      USER_APP_UPDATE_PERMISSION: 'user/app-access/',
    },
    USER: 'user',
    GLOBAL_SETTINGS: 'global-settings',
    DELETE: 'delete',
    RESEND_LINK: 'resend-link',
    APP_MODULE: {
      APP_MODULE: 'app-module',
      CREATE: 'app-module/create',
      UPDATE: 'app-module/update',
      DELETE: 'app-module/delete',
      USER: 'app-module/user',
    },
  },
  NFT: {
    DASHBOARD: 'dashboard',
    DEMO_REQUEST: 'demo-request',
    CATEGORY: 'category',
    NFT: 'nft',
    LABELS: 'labels',
    GLOBAL_SETTINGS: 'global-settings',
    BLOCKCHAIN: {
      GET_BLOCKCHAIN: 'blockchain',
      RANK_BLOCKCHAIN: 'blockchain/rank',
    },
  },
  UNIVERSE: {
    DASHBOARD: 'dashboard',
    REQUEST_CHART: 'dashboard/request-chart',
    NETWORKS: 'networks',
    PEERS: 'peers',
    CHANNELS: 'channels',
    INVITATIONS: 'invitations',
    CHAIN_CODES: 'chain-codes',
    CONTRACTS: 'contracts',
    INSTALLATIONS: 'contracts/channels',
    TEMPLATES: 'templates',
    APIS: 'apis',
    APPLICATIONS: 'applications',
    API_DESCRIPTIONS: 'api-descriptions',
    APIS_DESCRIPTIONS_INFO: 'api-descriptions/info',
    REQUEST_HISTORY: 'request-history',
    NETWORK_DOMAINS: 'network-domains',
    NETWORK_REGIONS: 'network-regions',
    GLOBAL_SETTINGS: 'global-settings',
  },
  BANJI: {
    DASHBOARD: 'dashboard',
    DIGITAL_TWIN: 'digital-twin',
    NEWS: 'news',
    NOTIFICATIONS: 'notifications',
    GLOBAL_SETTINGS: 'global-settings',
    REQUEST: 'customer-request',
    COUPONS: 'coupons',
    USERS: 'users',
    PLAN: 'pricing-plan',
  },
  BSTAMP: {
    DASHBOARD: 'dashboard',
    LABELS: 'labels',
    COUPON: 'coupon',
    USERS: 'users',
    ORGANIZATION: 'organization',
    USAGE: 'organization/usage',
    PRICING_PLAN: 'plan',
    GLOBAL_SETTINGS: 'global-settings',
  },
  STAKING: {
    APPLICATIONS: 'applications',
    BLOGS: 'blogs',
    CONTACT_US: 'contact-us',
    CATEGORY: 'category',
    AVAILABLE_APPS: 'available-apps',
    REQUEST_DEMO: 'request-demo',
    VALIDATORS: 'validators',
    DAPPS: 'dapps',
    LABELS: 'labels',
    MARKETPLACE: 'marketplace',
    GLOBAL_SETTINGS: 'global-settings',
  },
  BMESSAGE: {
    DASHBOARD: 'dashboard',
    LABELS: 'labels',
    GLOBAL_SETTINGS: 'global-settings',
  },
  BYOU: {
    USER_MANAGEMENT: 'users',
    LABELS: 'labels',
    GLOBAL_SETTINGS: 'global-settings',
  },
  BSIGN: {
    COUPONS: 'coupons',
    PRICING_PLAN: 'pricing-plan',
    LABELS: 'labels',
    GLOBAL_SETTINGS: 'global-settings',
  },
};
