import {
  ApartmentOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  BellOutlined,
  BlockOutlined,
  BoldOutlined,
  BoxPlotOutlined,
  CheckOutlined,
  ContactsOutlined,
  ContainerOutlined,
  CreditCardOutlined,
  DashboardOutlined,
  DollarCircleOutlined,
  DownloadOutlined,
  ForkOutlined,
  FundOutlined,
  GlobalOutlined,
  HddOutlined,
  HistoryOutlined,
  IdcardOutlined,
  IssuesCloseOutlined,
  PartitionOutlined,
  PicCenterOutlined,
  QuestionOutlined,
  ReadOutlined,
  SlidersOutlined,
  TagsOutlined,
  UserOutlined,
  UsergroupAddOutlined,
} from '@ant-design/icons';

export const Icon: { [key: string]: React.ElementType } = {
  'dashboard-management': DashboardOutlined,
  'admin-management': UserOutlined,
  'setting-management': GlobalOutlined,
  'kyc-management': IdcardOutlined,
  'user-management': UsergroupAddOutlined,
  'role-management': PartitionOutlined,
  'shortcut-management': AppstoreAddOutlined,
  'label-management': TagsOutlined,
  'notification-management': BellOutlined,
  'news-management': ReadOutlined,
  'dtwin-management': PicCenterOutlined,
  'plan-management': SlidersOutlined,
  'request-management': QuestionOutlined,
  'issue-management': IssuesCloseOutlined,
  'nft-management': BlockOutlined,
  'module-management': AppstoreOutlined,
  'blockchain-management': BlockOutlined,
  'category-management': HddOutlined,
  'coupon-management': ContainerOutlined,
  'reqdemo-management': IdcardOutlined,
  'contactus-management': ContactsOutlined,
  'group-management': UsergroupAddOutlined,
  'pollhistory-management': HistoryOutlined,
  'poll-management': BoxPlotOutlined,
  'voter-management': CreditCardOutlined,
  'blog-management': ContainerOutlined,
  'availapp-management': AppstoreOutlined,
  'validator-management': CheckOutlined,
  'reqapp-management': AppstoreAddOutlined,
  'mrktplc-management': ApartmentOutlined,
  'error-management': IssuesCloseOutlined,
  'api-management': BoxPlotOutlined,
  'application-management': BoxPlotOutlined,
  'chaincode-management': SlidersOutlined,
  'channel-management': UserOutlined,
  'contract-management': BoldOutlined,
  'network-management': PartitionOutlined,
  'orderer-management': TagsOutlined,
  'peer-management': DollarCircleOutlined,
  'reqhistory-management': IssuesCloseOutlined,
  'template-management': IssuesCloseOutlined,
  'universe-management': IssuesCloseOutlined,
  'tokenengine-management': IssuesCloseOutlined,
  'domain-management': BoxPlotOutlined,
  'region-management': IssuesCloseOutlined,
  'invitation-management': ForkOutlined,
  'installations-management': DownloadOutlined,
  'organizationusage-management': FundOutlined,
};
